<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #6F4E37; color: white; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { text-align: center; margin-top: 30px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>☕ Brew & Bean Co. Pro</h1>
        <h2>Sales Report</h2>
        <p>Generated: {{ now()->format('M d, Y H:i') }}</p>
    </div>

    @if(count($sales) > 0)
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Branch</th>
                    <th>Cashier</th>
                    <th>Customer</th>
                    <th>Total</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sales as $sale)
                <tr>
                    <td>{{ $sale->id }}</td>
                    <td>{{ $sale->sale_date->format('M d, Y H:i') }}</td>
                    <td>{{ $sale->branch->name }}</td>
                    <td>{{ $sale->user->name }}</td>
                    <td>{{ $sale->customer->name ?? 'Walk-in' }}</td>
                    <td>${{ number_format($sale->total_amount, 2) }}</td>
                    <td>{{ ucfirst($sale->sync_status) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        
        <div style="margin-top: 20px;">
            <p><strong>Total Sales:</strong> ${{ number_format($sales->sum('total_amount'), 2) }}</p>
            <p><strong>Total Transactions:</strong> {{ $sales->count() }}</p>
        </div>
    @else
        <p>No sales found for the selected criteria.</p>
    @endif

    <div class="footer">
        <p>Generated by Brew & Bean Co. Pro</p>
    </div>
</body>
</html>
